import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "blue", textAlign: "center" }}>
          <nav>
            <ul
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "22px",
              }}
            >
              <li>
                <Link href="/layoutExample/store">Store</Link>
              </li>
              <li>
                <Link href="/layoutExample/cart">cart</Link>
              </li>
              <li>
                <Link href="/layoutExample/payment">Payment</Link>
              </li>
              <li>
                <Link href="/transactions">Transactions</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
